#!/usr/bin/expect -f

proc send {ignore arg} {
	sleep .1
	exp_send -s -- $arg
}

set timeout -1
set send_slow {1 .1}

set user [lindex $argv 0]
set passwd [lindex $argv 1]
set db [lindex $argv 2]

spawn su - $user -c "db2 CREATE DATABASE $db; db2 UPDATE CLI CFG FOR SECTION $db USING PATCH2 6; db2 UPDATE CLI CFG FOR SECTION $db USING LONGDATACOMPAT 1"
match_max 100000
expect -exact "Password: "
send -- "$passwd\r"
expect eof
