<?php
require_once 'MDB2.php';
if(getdbType() == 'mysql' or getdbType() == 'mysqli') {
	$db_username = (isSet($DEFS['DB_USER'])) ? $DEFS['DB_USER'] : 'root';
	$db_password = (isSet($DEFS['DB_PASS'])) ? $DEFS['DB_PASS'] : 'Doc-4tron';

	$db_engine = getdbType(); 
	if(!defined('AUTOINC')) {
		define('AUTOINC', 'INT AUTO_INCREMENT');
		define('AUTOINC2', 'INT AUTO_INCREMENT');
		define('TEXT16M', 'MEDIUMTEXT');
		define('TEXT64K', 'TEXT');
		define('DATETIME', 'DATETIME DEFAULT 0');
		define('DATE', 'DATE');
		define('LIKE', 'LIKE');
	}
} elseif(getdbType() == 'db2') {
	$db_username = (isSet($DEFS['DB_USER'])) ? $DEFS['DB_USER'] : 'db2inst1';
	$db_password = (isSet($DEFS['DB_PASS'])) ? $DEFS['DB_PASS'] : 'docutron';

	$db_engine = 'odbc';
	$db_instance = 'db2inst1';
	if(!extension_loaded('odbc')) {
		dl('odbc.so');
	}
	if(!defined('AUTOINC')) {
		define('AUTOINC', 'INT GENERATED BY DEFAULT AS '.
			'IDENTITY(START WITH 1, INCREMENT BY 1)');
		define('AUTOINC2', 'INT GENERATED BY DEFAULT AS '.
			'IDENTITY(START WITH 20000, INCREMENT BY 1)');
		define('TEXT16M', 'CLOB(16M)');
		define('TEXT64K', 'CLOB(64K)');
		define('DATETIME', 'TIMESTAMP DEFAULT NULL');
		define('DATE', 'DATE');
		define('LIKE', 'LIKE');
	}
} elseif(getdbType() == 'pgsql') {
	$db_engine = 'pgsql';

	$db_username = (isSet($DEFS['DB_USER'])) ? $DEFS['DB_USER'] : 'postgres';
	$db_password = (isSet($DEFS['DB_PASS'])) ? $DEFS['DB_PASS'] : '';
	if(!defined('AUTOINC')) {
		define('AUTOINC', 'SERIAL');
		define('AUTOINC2', 'SERIAL');
		define('TEXT16M', 'TEXT');
		define('TEXT64K', 'TEXT');
		define('DATETIME', 'TIMESTAMP DEFAULT NULL');
		define('DATE', 'DATE');
		define('LIKE', 'ILIKE');
	}
} elseif(getdbType() == 'mssql') {
//	putenv ('SYBASE=/opt/lampp/lib');
//	putenv ('SYBPLATFORM=linux');
//	putenv ('LC_ALL=default');
//	putenv ('DSQUERY=SYBASE');
//	putenv ('TDSVER=80');
	$db_username = $DEFS['DB_USER'];
	$db_password = $DEFS['DB_PASS'];
	$db_engine = 'mssql';
	if(!defined('AUTOINC')) {
		define('AUTOINC', 'INT IDENTITY');
		define('AUTOINC2', 'INT IDENTITY(20000,1)');
		//Please do not set these to "TEXT NULL", it messes up table
		//creation.
		define('TEXT16M', 'TEXT');
		define('TEXT64K', 'TEXT');
		define('DATETIME', "DATETIME NULL DEFAULT NULL");
		define('DATE', 'SMALLDATETIME');
		define('LIKE', 'LIKE');
	}
} 
$db_host = getdbHost();
?>
